spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_store?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: cKOEBtEuLsBd172

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    open-in-view: off

  application:
    name: online-store-api

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

api:
  prefix: api/v1

jwt:
  expiration: 604800 # 1 week
  secret-key: Pu4XEgOUeq7YxMkj0isj/2bwxGXo3Gjw3+8R7I8I7vj5UjQimKolYFRvEhwpKkD9